language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - python setup.py sdist && cd dist && sudo pip install kalamari-0.1dev.tar.gz
  - pip install -e ".[dev]"
# command to run tests
script:
  - pytest
