language: python
python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - python setup.py sdist && cd dist && sudo pip install kalamari-0.1dev.tar.gz && cd ..
  - pip install -e ".[dev]"
  - pip install coveralls
# command to run tests
script:
  - coverage run -m pytest
  - coverage report
after_success:
  - coveralls
